# Generated by Django 5.0 on 2024-12-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_userquizattempt_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserQuizAttempt",
        ),
    ]
